# fly.toml app configuration file generated for tsukasa-robo on 2024-11-14T20:55:49Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tsukasa-robo'
primary_region = 'ord'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
